steps:
  - name: "Download"
    operations:
      - type: "download"
        name: "Download TOR vs CAR Game Recap"
        url: "https://www.youtube.com/watch?v=I2qYdtshu8U"
        output: "tor-vs-car-game-recap.mp4"

  - name: "Get music segment from the video"
    operations:
      - type: "convert"
        name: "Hell's Kitchen Sound"
        input: "/output/tor-vs-car-game-recap.mp4"
        output_format: "mp3"
        output: "tor-vs-car-game-recap.mp3"
      - type: "extract_voice"
        name: "Extract voice from the video"
        input: "/output/tor-vs-car-game-recap.mp3"
        target: "vocals"
        output: "tor-vs-car-game-recap-vocals.mp3"
      - type: "cut"
        input: "/output/tor-vs-car-game-recap.mp3"
        start: "00:06:38"
        end: "00:06:45"
        output: "tor-vs-car-game-recap-music-segment.mp3"
